import pytest
from unittest.mock import MagicMock
from app.services.study_session_service import StudySessionService
from app.services.mastery_service import DictionaryEntry


def test_generate_daily_review_cache_miss_and_hit(service):
    """
    Tests the complete Cache-Aside architecture.
    'service' is your MasteryService fixture from conftest.py!
    """
    # ---------------------------------------------------------
    # 1. ARRANGE: Set up the Stunt Doubles (Mocks)
    # ---------------------------------------------------------

    # Mock the LangChain Vector Store
    mock_vector_store = MagicMock()
    mock_document = MagicMock()
    mock_document.page_content = "El mae tiene mucho brete."
    mock_vector_store.similarity_search.return_value = [mock_document]

    # Mock the Gemini Adapter
    mock_generator = MagicMock()
    mock_generator.generate_flashcard.return_value = DictionaryEntry(
        node_id="brete",
        spanish="brete",
        english="work",
        example_sentences="El mae tiene mucho brete."
    )

    # Initialize the Orchestrator with the real SQLite but fake AI/VectorStore
    study_session = StudySessionService(
        mastery_service=service,
        generator_service=mock_generator,
        vector_store=mock_vector_store
    )

    # Tell the SRS Engine that "brete" is due right now
    service.update_node_mastery("brete", 1)

    # We also add "tuanis" and pretend we ALREADY generated it yesterday (Cache Setup)
    service.update_node_mastery("tuanis", 1)
    service.save_dictionary_entry(DictionaryEntry(
        node_id="tuanis", spanish="tuanis", english="cool", example_sentences="¡Qué tuanis!"
    ))

    # Fast forward time to tomorrow so both words are "Due"
    from datetime import datetime, timedelta
    future_time = (datetime.now() + timedelta(days=2)).isoformat()

    # ---------------------------------------------------------
    # 2. ACT: Run the daily review
    # ---------------------------------------------------------
    batch = study_session.generate_daily_review(current_time=future_time)

    # ---------------------------------------------------------
    # 3. ASSERT: Did the architecture behave correctly?
    # ---------------------------------------------------------
    assert len(batch) == 2

    # Check that "tuanis" was a CACHE HIT (loaded from SQLite)
    tuanis_card = next(card for card in batch if card.node_id == "tuanis")
    assert tuanis_card.english == "cool"

    # Check that "brete" was a CACHE MISS (generated by AI)
    brete_card = next(card for card in batch if card.node_id == "brete")
    assert brete_card.english == "work"

    # PRINCIPAL CHECK: Did the Orchestrator actually call the external services exactly ONCE for the missing word?
    mock_vector_store.similarity_search.assert_called_once_with("brete", k=3)
    mock_generator.generate_flashcard.assert_called_once()

    # Verify the Cache-Aside pattern worked: Is "brete" now saved in SQLite for next time?
    saved_entry = service.get_dictionary_entry("brete")
    assert saved_entry.spanish == "brete"